// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAidmut6tF6JS_Z9U6oPH75tggjdWRyLgM',
    appId: '1:1067958530696:web:56690f44229f16a686a53d',
    messagingSenderId: '1067958530696',
    projectId: 'bighouse-db',
    authDomain: 'bighouse-db.firebaseapp.com',
    storageBucket: 'bighouse-db.firebasestorage.app',
    measurementId: 'G-YS95374N2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZnB8EVPNjMyY7wD3xt5N3R-IFuzw2x5I',
    appId: '1:1067958530696:android:e6e2b37bee525e2686a53d',
    messagingSenderId: '1067958530696',
    projectId: 'bighouse-db',
    storageBucket: 'bighouse-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKq-_9D4Qo6FUMmtrNMdNpaJOeWkxYm7A',
    appId: '1:1067958530696:ios:eacf032a10677fe086a53d',
    messagingSenderId: '1067958530696',
    projectId: 'bighouse-db',
    storageBucket: 'bighouse-db.firebasestorage.app',
    iosBundleId: 'com.example.casaGrandeApp',
  );

}